-- DevBank Database Schema for Supabase
-- Execute this SQL in the Supabase SQL Editor

-- ==================== TABELAS ====================

-- Tabela de Cartões
CREATE TABLE IF NOT EXISTS cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  holder text not null,
  number text not null,
  expiry text not null,
  cvv text not null,
  brand text,
  balance numeric default 0,
  limit numeric default 0,
  color text,
  bank text,
  type text,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Tabela de Transações
CREATE TABLE IF NOT EXISTS transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text,
  amount numeric not null,
  date date not null,
  icon text,
  color text,
  type text not null,
  card_id bigint references cards(id) on delete set null,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Tabela de Bancos
CREATE TABLE IF NOT EXISTS banks (
  id bigint generated by default as identity primary key,
  name text not null,
  sub text,
  color text,
  logo text,
  connected boolean default false,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Tabela de Chaves PIX
CREATE TABLE IF NOT EXISTS pix_keys (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  key_type text not null,
  key_value text not null,
  is_primary boolean default false,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  unique(user_id, key_type, key_value)
);

-- ==================== ÍNDICES ====================

CREATE INDEX IF NOT EXISTS cards_user_id_idx ON cards(user_id);
CREATE INDEX IF NOT EXISTS transactions_user_id_idx ON transactions(user_id);
CREATE INDEX IF NOT EXISTS transactions_date_idx ON transactions(date);
CREATE INDEX IF NOT EXISTS transactions_category_idx ON transactions(category);
CREATE INDEX IF NOT EXISTS transactions_type_idx ON transactions(type);
CREATE INDEX IF NOT EXISTS pix_keys_user_id_idx ON pix_keys(user_id);

-- ==================== RLS (Row Level Security) ====================

-- Habilitar RLS em todas as tabelas
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE pix_keys ENABLE ROW LEVEL SECURITY;

-- ==================== POLÍTICAS - CARDS ====================

-- Usuários podem ver apenas seus próprios cartões
CREATE POLICY "Users can view own cards" ON cards
  FOR SELECT
  USING (auth.uid() = user_id);

-- Usuários podem inserir cartões
CREATE POLICY "Users can insert own cards" ON cards
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Usuários podem atualizar seus próprios cartões
CREATE POLICY "Users can update own cards" ON cards
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Usuários podem deletar seus próprios cartões
CREATE POLICY "Users can delete own cards" ON cards
  FOR DELETE
  USING (auth.uid() = user_id);

-- ==================== POLÍTICAS - TRANSACTIONS ====================

-- Usuários podem ver apenas suas próprias transações
CREATE POLICY "Users can view own transactions" ON transactions
  FOR SELECT
  USING (auth.uid() = user_id);

-- Usuários podem inserir transações
CREATE POLICY "Users can insert own transactions" ON transactions
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Usuários podem atualizar suas próprias transações
CREATE POLICY "Users can update own transactions" ON transactions
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Usuários podem deletar suas próprias transações
CREATE POLICY "Users can delete own transactions" ON transactions
  FOR DELETE
  USING (auth.uid() = user_id);

-- ==================== POLÍTICAS - BANKS ====================

-- Qualquer pessoa autenticada pode ver bancos (dados públicos/compartilhados)
CREATE POLICY "Authenticated users can view banks" ON banks
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Apenas administradores podem inserir bancos (role future-proofing)
CREATE POLICY "Only admins can insert banks" ON banks
  FOR INSERT
  WITH CHECK (false);

-- Apenas administradores podem atualizar bancos
CREATE POLICY "Only admins can update banks" ON banks
  FOR UPDATE
  USING (false);

-- Apenas administradores podem deletar bancos
CREATE POLICY "Only admins can delete banks" ON banks
  FOR DELETE
  USING (false);

-- ==================== POLÍTICAS - PIX KEYS ====================

-- Usuários podem ver apenas suas próprias chaves PIX
CREATE POLICY "Users can view own pix keys" ON pix_keys
  FOR SELECT
  USING (auth.uid() = user_id);

-- Usuários podem inserir suas próprias chaves PIX
CREATE POLICY "Users can insert own pix keys" ON pix_keys
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Usuários podem atualizar suas próprias chaves PIX
CREATE POLICY "Users can update own pix keys" ON pix_keys
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Usuários podem deletar suas próprias chaves PIX
CREATE POLICY "Users can delete own pix keys" ON pix_keys
  FOR DELETE
  USING (auth.uid() = user_id);

-- ==================== DADOS INICIAIS ====================

-- Bancos (dados públicos)
INSERT INTO banks (name, sub, color, logo, connected) VALUES
  ('Nubank', 'Conta corrente e crédito', '#820AD1', 'N', false),
  ('Itaú Unibanco', 'Conta corrente', '#EC7000', 'IU', false),
  ('Bradesco', 'Poupança', '#CC092F', 'BD', false),
  ('Caixa Econômica', 'Conta corrente', '#0066A1', 'CE', false),
  ('Banco do Brasil', 'Conta corrente', '#FFCC00', 'BB', false),
  ('Santander', 'Conta corrente', '#EC0000', 'ST', false),
  ('Inter', 'Conta digital', '#FF7A00', 'IN', false),
  ('C6 Bank', 'Conta digital', '#333', 'C6', false)
ON CONFLICT DO NOTHING;

-- ==================== FUNÇÕES AUXILIARES ====================

-- Atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers para updated_at
CREATE TRIGGER cards_update_timestamp BEFORE UPDATE ON cards
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER transactions_update_timestamp BEFORE UPDATE ON transactions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER banks_update_timestamp BEFORE UPDATE ON banks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ==================== VERIFICAÇÃO ====================

-- Para verificar se tudo foi criado corretamente, execute:
-- SELECT tablename FROM pg_tables WHERE schemaname = 'public';
-- SELECT * FROM pg_policies;
