-- SQL para adicionar chaves PIX ao banco existente
-- Se você já rodou database.sql, esta query adicionará suporte a PIX

-- Tabela de Chaves PIX
CREATE TABLE IF NOT EXISTS pix_keys (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  key_type text not null,
  key_value text not null,
  is_primary boolean default false,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  unique(user_id, key_type, key_value)
);

-- Índice para performance
CREATE INDEX IF NOT EXISTS pix_keys_user_id_idx ON pix_keys(user_id);

-- Habilitar RLS
ALTER TABLE pix_keys ENABLE ROW LEVEL SECURITY;

-- Políticas de Segurança
CREATE POLICY "Users can view own pix keys" ON pix_keys
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own pix keys" ON pix_keys
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own pix keys" ON pix_keys
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own pix keys" ON pix_keys
  FOR DELETE
  USING (auth.uid() = user_id);

-- Trigger para updated_at
CREATE TRIGGER pix_keys_update_timestamp BEFORE UPDATE ON pix_keys
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
